version: '3.8'

volumes:
  pg_data:
  static:
  pgadmin_data:

services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  pgadmin:
    image: dpage/pgadmin4:7.8
    restart: unless-stopped
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 5050:80
  backend:
    build: ./backend/
    restart: unless-stopped
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - static:/backend_static
  nginx:
    build: ./nginx/
    restart: unless-stopped
    env_file: .env
    volumes:
      - static:/static
    ports:
      - 8000:80
